### ISSUE TITLE
Create fully transparent version

### ISSUE THREAD

**Issue by infotexture** [dita-ot/logo#2]
The changes in #1 replaced the white wing detail and masking rectangle from the original designs with gray fills to match the background of the page header at https://www.dita-ot.org.

<img src="https://user-images.githubusercontent.com/129995/53605634-68d01780-3bb8-11e9-876f-fb5149306785.png" height="120px" />

Rather than creating multiple versions with different color masks for various backgrounds, it would be better if we could instead "punch out" the gray areas and any paths beneath them, so the transparent background shows in these areas as well. _(I suggest we leave the white fill in eye & beak.)_

This would allow the same design to be used in multiple applications, including those we may not anticipate today.

_(Tried implementing this in Inkscape today, but wasn't able to figure out how (yet?)._

@SanFanDocu If you know how to do this and have any time to spare, suggestions would be welcome.

**Comment by SanFanDocu** [comment]
New version available in b3f6d9492bc30ab761b476873670c9195e2894c4

In addition to the full transparency, I drew the wing a bit smoother and removed some micro path glitches.

I will create a dark-background version later. In that case I would preffer to make eye and beak transparent, too.

<img src="https://raw.githubusercontent.com/dita-ot/logo/b3f6d9492bc30ab761b476873670c9195e2894c4/png/dita-ot-logo.png" height="120px" />

**Comment by infotexture** [comment]
👍 Excellent, thanks. Much better with the smoother paths.

I'll push another commit to remove the obsolete “Jumbotron” versions, merge the result and create a separate issue for the dark-background version, which I think is a good idea.
